// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: department_service.proto

package department

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepartmentReqMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MemberId             int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	OrganizationCode     string                 `protobuf:"bytes,2,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	Page                 int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	DepartmentCode       string                 `protobuf:"bytes,5,opt,name=departmentCode,proto3" json:"departmentCode,omitempty"`
	ParentDepartmentCode string                 `protobuf:"bytes,6,opt,name=parentDepartmentCode,proto3" json:"parentDepartmentCode,omitempty"`
	Name                 string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DepartmentReqMessage) Reset() {
	*x = DepartmentReqMessage{}
	mi := &file_department_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentReqMessage) ProtoMessage() {}

func (x *DepartmentReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentReqMessage.ProtoReflect.Descriptor instead.
func (*DepartmentReqMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{0}
}

func (x *DepartmentReqMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *DepartmentReqMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *DepartmentReqMessage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepartmentReqMessage) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DepartmentReqMessage) GetDepartmentCode() string {
	if x != nil {
		return x.DepartmentCode
	}
	return ""
}

func (x *DepartmentReqMessage) GetParentDepartmentCode() string {
	if x != nil {
		return x.ParentDepartmentCode
	}
	return ""
}

func (x *DepartmentReqMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DepartmentMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code             string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,3,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CreateTime       string                 `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Pcode            string                 `protobuf:"bytes,6,opt,name=pcode,proto3" json:"pcode,omitempty"`
	Path             string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DepartmentMessage) Reset() {
	*x = DepartmentMessage{}
	mi := &file_department_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentMessage) ProtoMessage() {}

func (x *DepartmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentMessage.ProtoReflect.Descriptor instead.
func (*DepartmentMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{1}
}

func (x *DepartmentMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepartmentMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DepartmentMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *DepartmentMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepartmentMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *DepartmentMessage) GetPcode() string {
	if x != nil {
		return x.Pcode
	}
	return ""
}

func (x *DepartmentMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDepartmentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DepartmentMessage   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentMessage) Reset() {
	*x = ListDepartmentMessage{}
	mi := &file_department_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentMessage) ProtoMessage() {}

func (x *ListDepartmentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_department_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentMessage.ProtoReflect.Descriptor instead.
func (*ListDepartmentMessage) Descriptor() ([]byte, []int) {
	return file_department_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDepartmentMessage) GetList() []*DepartmentMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListDepartmentMessage) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_department_service_proto protoreflect.FileDescriptor

const file_department_service_proto_rawDesc = "" +
	"\n" +
	"\x18department_service.proto\x12\x15department.service.v1\"\xfe\x01\n" +
	"\x14DepartmentReqMessage\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12*\n" +
	"\x10organizationCode\x18\x02 \x01(\tR\x10organizationCode\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12&\n" +
	"\x0edepartmentCode\x18\x05 \x01(\tR\x0edepartmentCode\x122\n" +
	"\x14parentDepartmentCode\x18\x06 \x01(\tR\x14parentDepartmentCode\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"\xc1\x01\n" +
	"\x11DepartmentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12*\n" +
	"\x10OrganizationCode\x18\x03 \x01(\tR\x10OrganizationCode\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"createTime\x18\x05 \x01(\tR\n" +
	"createTime\x12\x14\n" +
	"\x05pcode\x18\x06 \x01(\tR\x05pcode\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\"k\n" +
	"\x15ListDepartmentMessage\x12<\n" +
	"\x04list\x18\x01 \x03(\v2(.department.service.v1.DepartmentMessageR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xba\x02\n" +
	"\x11DepartmentService\x12_\n" +
	"\x04Save\x12+.department.service.v1.DepartmentReqMessage\x1a(.department.service.v1.DepartmentMessage\"\x00\x12_\n" +
	"\x04Read\x12+.department.service.v1.DepartmentReqMessage\x1a(.department.service.v1.DepartmentMessage\"\x00\x12c\n" +
	"\x04List\x12+.department.service.v1.DepartmentReqMessage\x1a,.department.service.v1.ListDepartmentMessage\"\x00B3Z1project-project/pkg/service/department.service.v1b\x06proto3"

var (
	file_department_service_proto_rawDescOnce sync.Once
	file_department_service_proto_rawDescData []byte
)

func file_department_service_proto_rawDescGZIP() []byte {
	file_department_service_proto_rawDescOnce.Do(func() {
		file_department_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_department_service_proto_rawDesc), len(file_department_service_proto_rawDesc)))
	})
	return file_department_service_proto_rawDescData
}

var file_department_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_department_service_proto_goTypes = []any{
	(*DepartmentReqMessage)(nil),  // 0: department.service.v1.DepartmentReqMessage
	(*DepartmentMessage)(nil),     // 1: department.service.v1.DepartmentMessage
	(*ListDepartmentMessage)(nil), // 2: department.service.v1.ListDepartmentMessage
}
var file_department_service_proto_depIdxs = []int32{
	1, // 0: department.service.v1.ListDepartmentMessage.list:type_name -> department.service.v1.DepartmentMessage
	0, // 1: department.service.v1.DepartmentService.Save:input_type -> department.service.v1.DepartmentReqMessage
	0, // 2: department.service.v1.DepartmentService.Read:input_type -> department.service.v1.DepartmentReqMessage
	0, // 3: department.service.v1.DepartmentService.List:input_type -> department.service.v1.DepartmentReqMessage
	1, // 4: department.service.v1.DepartmentService.Save:output_type -> department.service.v1.DepartmentMessage
	1, // 5: department.service.v1.DepartmentService.Read:output_type -> department.service.v1.DepartmentMessage
	2, // 6: department.service.v1.DepartmentService.List:output_type -> department.service.v1.ListDepartmentMessage
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_department_service_proto_init() }
func file_department_service_proto_init() {
	if File_department_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_department_service_proto_rawDesc), len(file_department_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_department_service_proto_goTypes,
		DependencyIndexes: file_department_service_proto_depIdxs,
		MessageInfos:      file_department_service_proto_msgTypes,
	}.Build()
	File_department_service_proto = out.File
	file_department_service_proto_goTypes = nil
	file_department_service_proto_depIdxs = nil
}
